version: "3.7"

volumes:
  db_data:

services:

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: JaydenPears120905
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 9432:5432
