# Generated by Django 4.1.6 on 2023-09-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('is_free', models.BooleanField(default=True, verbose_name='Is free?')),
                ('cost', models.CharField(max_length=100, verbose_name='Cost')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
        ),
    ]
