# Generated by Django 4.1.6 on 2023-10-14 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'ClubInfo',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('short_description', models.CharField(max_length=300, verbose_name='Short description')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Image')),
                ('date', models.DateTimeField(verbose_name='Date and time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('category', models.CharField(choices=[('post', 'Post'), ('afisha', 'Afisha')], default='post', max_length=50, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Image')),
                ('is_free', models.BooleanField(default=True, verbose_name='Is free?')),
                ('cost', models.CharField(blank=True, max_length=100, verbose_name='Cost')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SectionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('section', models.ManyToManyField(related_name='groups', to='core.section')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='FIO')),
                ('vk_id', models.CharField(blank=True, max_length=100, verbose_name='VK id')),
                ('tg_id', models.CharField(blank=True, max_length=100, verbose_name='Telegram id')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Image')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone number')),
                ('job', models.ManyToManyField(related_name='personal', to='core.job')),
                ('section', models.ManyToManyField(blank=True, related_name='personal', to='core.section')),
            ],
            options={
                'verbose_name': 'Personal',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PeriodicLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'понедельник'), ('1', 'вторник'), ('2', 'среда'), ('3', 'четверг'), ('4', 'пятница'), ('5', 'суббота'), ('6', 'воскресение')], default='0', max_length=11, verbose_name='Day of weak')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodiclessons', to='core.sectiongroup')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodiclessons', to='core.section')),
            ],
            options={
                'verbose_name': 'PeriodicLesson',
                'verbose_name_plural': 'PeriodicLessons',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='core.sectiongroup')),
                ('periodic_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.periodiclesson')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='core.section')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ('id',),
            },
        ),
    ]
