# Generated by Django 4.1.6 on 2023-10-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodiclesson',
            name='start_date',
            field=models.DateField(default='2006-11-11', verbose_name='Start date'),
            preserve_default=False,
        ),
    ]
