# Generated by Django 4.1.6 on 2023-09-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_afisha_clubinfo_management_partner_post_trainer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Afisha',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('post', 'Post'), ('afisha', 'Afisha')], default='post', max_length=50, verbose_name='Category'),
        ),
    ]
