# Generated by Django 4.1.6 on 2023-09-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_job_personal_delete_management_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.CharField(max_length=300, verbose_name='Short description'),
        ),
    ]
