# Generated by Django 4.1.6 on 2023-09-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Section',
            field=models.ManyToManyField(blank=True, related_name='personal', to='core.section'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='tg_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram id'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='vk_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='VK id'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='section',
            name='cost',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image'),
        ),
    ]
