# Generated by Django 4.1.6 on 2023-09-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_lesson_date_alter_partner_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job',
        ),
        migrations.AlterField(
            model_name='personal',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='job',
            field=models.ManyToManyField(related_name='job', to='core.job'),
        ),
    ]
