# Generated by Django 4.1.6 on 2023-09-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_job_job_alter_personal_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='text',
            field=models.CharField(default='test', max_length=100, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
