# Generated by Django 4.1.6 on 2023-09-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_section_personal_section_alter_personal_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='Group',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='sectiongroup',
            old_name='Section',
            new_name='section',
        ),
    ]
