# Generated by Django 4.1.6 on 2023-09-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_group_lesson_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
